
Verditer = Verditer or {}
Verditer.zenimax = Verditer.zenimax or {}
local Verditer = Verditer

Verditer.zenimax.constants = {}
local M = Verditer.zenimax.constants

M.EVENT_ADD_ON_LOADED              = EVENT_ADD_ON_LOADED
M.EVENT_COMBAT_EVENT               = EVENT_COMBAT_EVENT
M.EVENT_PLAYER_ACTIVATED           = EVENT_PLAYER_ACTIVATED
M.EVENT_PLAYER_DEACTIVATED         = EVENT_PLAYER_DEACTIVATED
M.EVENT_PLAYER_COMBAT_STATE        = EVENT_PLAYER_COMBAT_STATE

M.EVENT_POWER_UPDATE               = EVENT_POWER_UPDATE
M.EVENT_PLAYER_DEAD                = EVENT_PLAYER_DEAD
M.EVENT_PLAYER_ALIVE               = EVENT_PLAYER_ALIVE

M.REGISTER_FILTER_SOURCE_COMBAT_UNIT_TYPE = REGISTER_FILTER_SOURCE_COMBAT_UNIT_TYPE
M.REGISTER_FILTER_TARGET_COMBAT_UNIT_TYPE = REGISTER_FILTER_TARGET_COMBAT_UNIT_TYPE
M.REGISTER_FILTER_COMBAT_RESULT           = REGISTER_FILTER_COMBAT_RESULT
M.REGISTER_FILTER_IS_ERROR                = REGISTER_FILTER_IS_ERROR
M.REGISTER_FILTER_UNIT_TAG                = REGISTER_FILTER_UNIT_TAG
M.REGISTER_FILTER_POWER_TYPE              = REGISTER_FILTER_POWER_TYPE

M.COMBAT_UNIT_TYPE_PLAYER     = COMBAT_UNIT_TYPE_PLAYER
M.COMBAT_UNIT_TYPE_PLAYER_PET = COMBAT_UNIT_TYPE_PLAYER_PET
M.COMBAT_UNIT_TYPE_GROUP      = COMBAT_UNIT_TYPE_GROUP

M.COMBAT_MECHANIC_FLAGS_HEALTH = COMBAT_MECHANIC_FLAGS_HEALTH

M.ACTION_RESULT_DAMAGE              = ACTION_RESULT_DAMAGE
M.ACTION_RESULT_DOT_TICK            = ACTION_RESULT_DOT_TICK
M.ACTION_RESULT_CRITICAL_DAMAGE     = ACTION_RESULT_CRITICAL_DAMAGE
M.ACTION_RESULT_DOT_TICK_CRITICAL   = ACTION_RESULT_DOT_TICK_CRITICAL
M.ACTION_RESULT_BLOCKED_DAMAGE      = ACTION_RESULT_BLOCKED_DAMAGE
M.ACTION_RESULT_FALL_DAMAGE         = ACTION_RESULT_FALL_DAMAGE
M.ACTION_RESULT_DAMAGE_SHIELDED     = ACTION_RESULT_DAMAGE_SHIELDED

M.ACTION_RESULT_DODGED              = ACTION_RESULT_DODGED
M.ACTION_RESULT_MISS                = ACTION_RESULT_MISS
M.ACTION_RESULT_IMMUNE              = ACTION_RESULT_IMMUNE
M.ACTION_RESULT_BLOCKED             = ACTION_RESULT_BLOCKED
M.ACTION_RESULT_REFLECTED           = ACTION_RESULT_REFLECTED
M.ACTION_RESULT_PARRIED             = ACTION_RESULT_PARRIED
M.ACTION_RESULT_DIED                = ACTION_RESULT_DIED
M.ACTION_RESULT_KILLING_BLOW        = ACTION_RESULT_KILLING_BLOW

M.DAMAGE_TYPE_NONE     = DAMAGE_TYPE_NONE
M.DAMAGE_TYPE_GENERIC  = DAMAGE_TYPE_GENERIC
M.DAMAGE_TYPE_PHYSICAL = DAMAGE_TYPE_PHYSICAL
M.DAMAGE_TYPE_FIRE     = DAMAGE_TYPE_FIRE
M.DAMAGE_TYPE_SHOCK    = DAMAGE_TYPE_SHOCK
M.DAMAGE_TYPE_OBLIVION = DAMAGE_TYPE_OBLIVION
M.DAMAGE_TYPE_COLD     = DAMAGE_TYPE_COLD
M.DAMAGE_TYPE_EARTH    = DAMAGE_TYPE_EARTH
M.DAMAGE_TYPE_MAGIC    = DAMAGE_TYPE_MAGIC
M.DAMAGE_TYPE_DROWN    = DAMAGE_TYPE_DROWN
M.DAMAGE_TYPE_DISEASE  = DAMAGE_TYPE_DISEASE
M.DAMAGE_TYPE_POISON   = DAMAGE_TYPE_POISON
M.DAMAGE_TYPE_BLEED    = DAMAGE_TYPE_BLEED


M.TOPLEFT     = TOPLEFT
M.TOP         = TOP
M.TOPRIGHT    = TOPRIGHT
M.LEFT        = LEFT
M.CENTER      = CENTER
M.RIGHT       = RIGHT
M.BOTTOMLEFT  = BOTTOMLEFT
M.BOTTOM      = BOTTOM
M.BOTTOMRIGHT = BOTTOMRIGHT


M.CT_TEXTURE  = CT_TEXTURE
M.CT_LABEL    = CT_LABEL
M.CT_BACKDROP = CT_BACKDROP
M.CT_CONTROL  = CT_CONTROL


M.TEXT_ALIGN_LEFT   = TEXT_ALIGN_LEFT
M.TEXT_ALIGN_CENTER = TEXT_ALIGN_CENTER
M.TEXT_ALIGN_RIGHT  = TEXT_ALIGN_RIGHT
M.TEXT_ALIGN_TOP    = TEXT_ALIGN_TOP
M.TEXT_ALIGN_BOTTOM = TEXT_ALIGN_BOTTOM


M.GuiRoot = GuiRoot
M.SOUNDS  = SOUNDS
